// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	STEAM_USER_QUEUE: Queue<any>;
	DB: D1Database;
	API_KEY: string;
}
