// Generated by Wrangler by running `wrangler types`

type Message = {
	id: string;
	userId: string;
	steamId: string;
};

interface Env {
	API_KEY: string;
	BATCH_SIZE: string;
	BUCKET: R2Bucket;
	DELAY_SECONDS: string;
	DB: D1Database;
	STEAM_USER_QUEUE: Queue<Message>;
}
